// @flow

import type { Validation }     from "components/forms/Validation.type"
import type { ContainerProps } from "styles/types"
import * as React              from "react"

export type SelectorItemKey = string
export type SelectorOption = any
export type OnMultiSelectItemRemoveFunc<T = SelectorItemKey> = (T) => void
export type OnItemSelectedFunc<T = SelectorItemKey | { [string] :any }> = (T) => void

export type SelectorProps = {
    label? :string,
    options :Array<SelectorOption>,
    optionsKeyMap? :{ [SelectorItemKey] :SelectorOption },
    keyField :string,
    valueField :string,
    selectedKey? :SelectorItemKey,
    message? :string,
    emptyState? :string,
    hint? :string,
    onChange? :OnItemSelectedFunc<>,
    onStateChange :() => void,
    invalidOnNoSelection? :boolean,
    validation :Validation,
    flat? :boolean,
    open? :boolean,
} & ContainerProps

export type RefinedSelectorProps = {
    // should be generated by HOC automatically
    optionNodes :Array<React.Node>
} & SelectorProps
