on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
name: NPM Publish
permissions:
  id-token: write # Required for OIDC
  contents: write
jobs:
  publish:
    env:
      ACTION_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          # node-version-file: ".node-version"
      - name: Publish to NPM Registry
        timeout-minutes: 10

        run: |
          echo "Publishing to NPM Registry"
          npm ci
          npm publish --access public
